name: LifeMultimedia
favicon: null
layout_spectrum: 0.49913
typography_spectrum: 0.6489215535111725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4233f'
    - '#231f20'
    - '#040707'
    - '#aa002b'
    - '#ff0000'
  brandStrength: 0.4375
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
