name: LifeMultimedia
favicon: null
layout_spectrum: 0.6486247631255537
typography_spectrum: 0.6489215535111725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4233f'
    - '#231f20'
    - '#040707'
    - '#aa002b'
    - '#ff0000'
  brandStrength: 0.03515909495763481
  lightness: 0.04571796045638621
  saturation: 0.257114480715245
  rhythmicContrast: 0.7166245426051319
purpose: []
