typography_spectrum: 0.6489215535111725
color:
  brandColors:
    - '#c4233f'
    - '#231f20'
    - '#040707'
    - '#aa002b'
    - '#ff0000'
  brandStrength: 0.4375
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49913
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Han Tak
  email: Han@LifeMultimedia.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dd50e606-a1ff-406a-9286-c06d31cd1acd.png
name: LifeMultimedia
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Caps
    url: 'https://www.facebook.com/capsonthewater/videos'
    type: external
  - name: Sunset
    url: 'https://www.facebook.com/SunsetGrilleA1a/videos'
    type: external
  - name: Habitat
    url: 'https://www.facebook.com/habitat.st.augustine/videos'
    type: external
  - name: Current Projects
    url: 'https://vimeo.com/user48722357/videos'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/06429f99-61f3-43d9-a861-4ab69eec4659.png
title: Your Story to Life
description: Brought to Life
purpose: []
